---
# istio-system namespace
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
---
# nginx-test namespace
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test
  labels:
    name: nginx-test
    environment: test
    istio-injection: enabled  # Enables Istio sidecar injection
