apiVersion: v1
kind: Service
metadata:
  name: web-microservice
spec:
  type: LoadBalancer
  selector:
    app: web-microservice
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080